const {test}=require('node:test');const assert=require('node:assert/strict');const {join}=require('node:path');const {decideCars,defaultDecisionInput}=require(join(process.env.CARWISE_CHECKS_DIR,'decision-engine.js'));const {normalizeCar,jsonTemplate}=require(join(process.env.CARWISE_CHECKS_DIR,'car-import.js'));
function car(){const d=structuredClone(jsonTemplate.cars[0]);d.id='test-car-automatic';d.brand='Test';d.model='Car';d.variant='Automatic';d.status='published';d.exShowroomPrice={...d.exShowroomPrice,value:1500000,source:'https://example.com/specifications'};d.seating={...d.seating,value:5,source:'https://example.com/specifications'};for(const key of Object.keys(d.scores))d.scores[key]={...d.scores[key],score:8,explanation:'Fixture assessment',sources:['Fixture']};return normalizeCar(d)}
const input={...defaultDecisionInput,priceBasis:'ex-showroom',budget:2000000};
test('Typed inputs reject zero weights and non-finite or out-of-range values',()=>{assert.throws(()=>decideCars([car()],{...input,weights:Array(10).fill(0)}));assert.throws(()=>decideCars([car()],{...input,budget:NaN}));assert.throws(()=>decideCars([car()],{...input,cityShare:101}));assert.throws(()=>decideCars([car()],{...input,unexpected:true}))});
test('Hard constraints exclude cars and matching sourced cars are eligible',()=>{const c=car();const r=decideCars([c],input);assert.equal(r.decisions[0].status,'eligible');assert.equal(r.decisions[0].score,80);assert.equal(r.choice.action,'compare_candidates');const rejected=decideCars([c],{...input,budget:1000000,seats:7}).decisions[0];assert.equal(rejected.status,'excluded');assert.deepEqual(rejected.checks.filter(c=>c.state==='fail').map(c=>c.key),['budget','seats'])});
test('Missing priority scores produce honest bounds instead of renormalized scores',()=>{const c=car();c.record.scores.comfort.score=null;const d=decideCars([c],{...input,weights:[0,50,0,0,50,0,0,0,0,0]}).decisions[0];assert.equal(d.status,'review');assert.equal(d.score,null);assert.deepEqual(d.scoreRange,[40,90]);assert.equal(d.scoreCoverage,50);assert.equal(d.factors[1].contribution,null)});
test('Independent crash-test evidence and standard feature availability cannot be inferred',()=>{const c=car();let d=decideCars([c],{...input,requireIndependentSafety:true,requiredFeatures:['LED headlights']}).decisions[0];assert.equal(d.status,'review');assert.equal(d.checks.find(x=>x.key==='safety').state,'unknown');c.record.features[0].status='optional';d=decideCars([c],{...input,requiredFeatures:['LED headlights']}).decisions[0];assert.equal(d.status,'excluded');c.record.features[0].status='standard';assert.equal(decideCars([c],{...input,requiredFeatures:['LED headlights']}).decisions[0].status,'eligible')});
test('Demo data requires review; strict mode excludes demos; unavailable cost stays null',()=>{const c=car();c.record.dataMode='demo';const d=decideCars([c],input).decisions[0];assert.equal(d.status,'review');assert.equal(d.annualEnergyCost,null);assert.equal(d.fiveYearOwnership,null);assert.equal(decideCars([c],{...input,includeDemo:false}).decisions[0].status,'excluded');const strict=decideCars([car()],{...input,priceBasis:'on-road',allowEstimatedPrices:false}).decisions[0];assert.equal(strict.priceEstimated,true);assert.equal(strict.status,'review')});
test('Route-weighted energy costs use consumption; five-year insurance counts four renewals',()=>{const c=car();const d=c.record;d.realWorldMileage.city.value=10;d.realWorldMileage.highway.value=20;d.ownership.annualMaintenance.value=6000;d.ownership.annualInsurance.value=20000;d.onRoadPrice.Hyderabad={...d.exShowroomPrice,value:1800000};const out=decideCars([c],{...input,annualKm:10000,cityShare:70,energyPrices:{Petrol:100,Diesel:90,CNG:80,EV:8}}).decisions[0];assert.equal(out.annualEnergyCost,85000);assert.equal(out.fiveYearOwnership,2335000);assert.equal(out.scoreCoverage,100)});
test('Stable rankings ignore input order; unknown constraints never become purchase approvals',()=>{const a=car(),b=car();b.id='another-car';b.record.id=b.id;a.record.seating.value=null;const first=decideCars([a,b],input),second=decideCars([b,a],input);assert.deepEqual(first.decisions.map(x=>x.carId),second.decisions.map(x=>x.carId));assert.equal(first.decisions[0].carId,b.id);assert.equal(first.decisions[1].action,'review_data')});
