'use client';
import {useMemo,useState} from 'react';
import {ArrowLeft,Info} from 'lucide-react';
import TalkingGuide,{type GuideScenario} from './talking-guide';
import {scenarioNarration} from '@/lib/scenario-narration';
import {domainConfig,suggestMoney,suggestScore,type Domain,type SuggestRecord} from '@/lib/suggest-catalogue';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function CategoryMira({domain,records,weights,context='',onBack}:{domain:Domain;records:SuggestRecord[];weights:number[];context?:string;onBack?:()=>void}){const [inspect,setInspect]=useState<string|null>(null);const config=domainConfig[domain];const scenario=useMemo<GuideScenario>(()=>({label:domain==='homes'?'Home':domain==='education'?'Institution':'Travel option',options:records.map(r=>({id:r.id,name:r.name})),topics:[{id:'shortlist',label:'My shortlist'},{id:'why',label:'Why this option?'},{id:'tradeoffs',label:'Trade-offs'},{id:'cost',label:domain==='education'?'Fees & budget':'Price & budget'},{id:'safety',label:'Verify evidence'},{id:'compare',label:'Compare first two'},{id:'features',label:domain==='education'?'Course & campus':domain==='homes'?'Space & amenities':'Profile & experience'},...(domain==='travel'?[{id:'efficiency' as const,label:'Seasonal fit'}]:[])],narrate:(topic,id,q)=>scenarioNarration(domain,records,weights,topic,id,q,context),onInspect:setInspect}),[domain,records,weights,context]);const record=records.find(r=>r.id===inspect);
return <main className="page decision-page category-mira"><div className="section-top"><div><span className="eyebrow muted">MIRA · {config.scope.toUpperCase()}</span><h1>{config.title}</h1><p>Listen to the reasons, understand the trade-offs.</p></div>{onBack&&<button className="secondary" onClick={onBack}><ArrowLeft size={15}/>Back to results</button>}</div><TalkingGuide scenario={scenario}><section className="decision-results"><div className="suggest-disclosure"><Info size={18}/><p>Current category data is illustrative. Mira explains supplied profiles and calculations; she cannot verify availability or missing facts.</p></div><h2>Options in this conversation</h2>{records.map(r=><article className="panel" key={r.id}><span className="badge">DEMO · {r.kind}</span><h3>{r.name}</h3><p>{r.location} · {suggestMoney(r.price)} · {r.priceLabel}</p><p>My score: <b>{suggestScore(r,weights)}/100</b></p><button className="text-link" onClick={()=>setInspect(r.id)}>Inspect the evidence</button></article>)}</section></TalkingGuide><Dialog open={!!record} onOpenChange={o=>!o&&setInspect(null)}><DialogContent><DialogTitle>{record?.name}</DialogTitle><DialogDescription>Demo profile · independent evidence unavailable</DialogDescription>{record&&<><p>{record.summary}</p>{config.criteria.map((c,i)=><p key={c}>{c}: {record.scores[i]}/10 · demo assessment</p>)}{Object.entries(record.attributes).map(([k,v])=><p key={k}>{k}: {v}</p>)}<p>Last updated: {record.lastUpdated}. Verify all facts and current prices before deciding.</p></>}</DialogContent></Dialog></main>}
