'use client';
import {useEffect,useRef,useState} from 'react';
import {cueAt,type VisemeCue,type MiraEmotion} from '@/lib/mira-speech';
import {energyAt,smoothValue,type SpeechEnergy} from '@/lib/mira-motion';
export type MiraPlayback={audio:HTMLAudioElement|null;cues:VisemeCue[];energy?:SpeechEnergy;elapsed:number};
export default function MiraAvatar({playback,motion,topic,emotion}:{playback:()=>MiraPlayback;motion:boolean;topic:string;emotion:MiraEmotion}){
const container=useRef<HTMLDivElement>(null),canvas=useRef<HTMLCanvasElement>(null),latest=useRef({playback,motion,topic,emotion});latest.current={playback,motion,topic,emotion};const [ready,setReady]=useState(false);
useEffect(()=>{const host=container.current,surface=canvas.current;if(!host||!surface)return;const ctx=surface.getContext('2d');if(!ctx)return;let cancelled=false,loop=0,atlasReady=false,portraitReady=false,width=0,height=0,last=0,energy=0,frame=0,previous=0,blend=1;const portrait=new Image(),atlas=new Image();const patches:HTMLCanvasElement[]=[];portrait.decoding='async';atlas.decoding='async';portrait.onload=()=>{portraitReady=true;setReady(true)};atlas.onload=()=>{const cw=atlas.naturalWidth/3,ch=atlas.naturalHeight/2;for(let i=0;i<6;i++){const centers=[[.54,.545],[.485,.554],[.48,.55],[.54,.545],[.487,.545],[.487,.529]];const [cx,cy]=centers[i];const patch=document.createElement('canvas');patch.width=256;patch.height=128;const p=patch.getContext('2d')!;p.drawImage(atlas,(i%3)*cw+cw*(cx-.125),Math.floor(i/3)*ch+ch*(cy-.08),cw*.25,ch*.16,0,0,256,128);p.globalCompositeOperation='destination-in';p.save();p.translate(128,64);p.scale(2,1);const feather=p.createRadialGradient(0,0,25,0,0,64);feather.addColorStop(0,'#fff');feather.addColorStop(.82,'#fff');feather.addColorStop(1,'#fff0');p.fillStyle=feather;p.fillRect(-64,-64,128,128);p.restore();patches.push(patch)}atlasReady=true};portrait.src='/avatars/mira-reference-portrait.png';atlas.src='/avatars/mira-speaking-atlas.png';const resize=()=>{width=host.clientWidth;height=host.clientHeight;const ratio=Math.min(window.devicePixelRatio||1,1.5);surface.width=Math.round(width*ratio);surface.height=Math.round(height*ratio);ctx.setTransform(ratio,0,0,ratio,0,0)};const observer=new ResizeObserver(resize);observer.observe(host);resize();
function placement(){const scale=Math.min(width/portrait.naturalWidth,height/portrait.naturalHeight);const w=portrait.naturalWidth*scale,h=portrait.naturalHeight*scale;return {x:(width-w)/2,y:height-h,w,h}}
function drawCell(index:number,opacity:number){if(!atlasReady||!portraitReady||index===0||opacity<=0)return;const {x,y,w,h}=placement();ctx!.globalAlpha=opacity;ctx!.drawImage(patches[index],x+w*(.512-.1),y+h*(.398-.064),w*.2,h*.128);ctx!.globalAlpha=1}
function render(now:number){if(cancelled)return;const dt=Math.min(.05,last?(now-last)/1000:.016);last=now;const {audio,cues,energy:envelope,elapsed}=latest.current.playback();const speaking=!!audio&&!audio.paused&&!audio.ended;const time=speaking?audio.currentTime:0,signal=speaking?energyAt(envelope,time):0;energy=smoothValue(energy,signal,dt,16);const next=speaking&&signal>.07?cueAt(cues,time):0;if(next!==frame){previous=frame;frame=next;blend=0}blend=Math.min(1,blend+dt/ .085);ctx!.clearRect(0,0,width,height);ctx!.save();const moving=latest.current.motion&&!document.hidden;const tilt=moving?Math.sin(now/4200)*.002+(speaking?Math.sin((elapsed+time)*1.7)*.003:0):0;const lift=moving?Math.sin(now/1600)*.65:0;ctx!.translate(width/2,height*.8+lift);ctx!.rotate(tilt);ctx!.translate(-width/2,-height*.8);if(portraitReady){const {x,y,w,h}=placement();ctx!.drawImage(portrait,x,y,w,h)}drawCell(previous,1-blend);drawCell(frame,blend);ctx!.restore();host!.dataset.speaking=String(speaking);host!.dataset.articulation=String(frame===0?0:energy.toFixed(2));host!.dataset.renderer='portrait';loop=requestAnimationFrame(render)}loop=requestAnimationFrame(render);return()=>{cancelled=true;cancelAnimationFrame(loop);observer.disconnect();portrait.onload=null;atlas.onload=null;};},[]);
return <div className="mira-stage mira-portrait-stage" role="img" aria-label="Mira, SuggestWise’s animated portrait presenter" data-renderer={ready?'portrait':'loading'}><div className="mira-stage-light" aria-hidden="true"/><div ref={container} className="mira-canvas"><canvas ref={canvas} aria-hidden="true"/></div><span className="mira-portrait-badge" aria-hidden="true">MIRA</span>{!ready&&<span className="mira-portrait-loading" role="status">Preparing Mira…</span>}</div>}
