'use client';
import {useEffect,useRef,useState} from 'react';
import type {VisemeCue} from '@/lib/mira-speech';
import {blinkAt,gestureAt,smoothValue,speechWeights} from '@/lib/mira-motion';
export type MiraPlayback={audio:HTMLAudioElement|null;cues:VisemeCue[]};
export default function MiraAvatar({playback,motion,topic}:{playback:()=>MiraPlayback;motion:boolean;topic:string}){
const container=useRef<HTMLDivElement>(null),latest=useRef({playback,motion,topic});latest.current={playback,motion,topic};const [status,setStatus]=useState<'loading'|'ready'|'fallback'>('loading');
useEffect(()=>{let cancelled=false,dispose=()=>{};async function initialize(){try{
const THREE=await import('three');const {GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js');const {MeshoptDecoder}=await import('three/addons/libs/meshopt_decoder.module.js');if(cancelled||!container.current)return;
const host=container.current,scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(29,1,.1,20);camera.position.set(0,1.46,2.05);camera.lookAt(0,1.39,0);
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
scene.add(new THREE.HemisphereLight(0xffffff,0x7785a3,2.2));const key=new THREE.DirectionalLight(0xffeee0,2.6);key.position.set(2,3,4);scene.add(key);const fill=new THREE.DirectionalLight(0xd9e9ff,1.4);fill.position.set(-3,1.8,2);scene.add(fill);const rim=new THREE.DirectionalLight(0x94baff,2);rim.position.set(1,2,-3);scene.add(rim);
const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder);let model:import('three').Group|undefined;let loop=0;const observer=new ResizeObserver(()=>resize());function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}observer.observe(host);resize();
function cleanup(){cancelAnimationFrame(loop);observer.disconnect();if(model)model.traverse(object=>{const mesh=object as import('three').Mesh;if(mesh.isMesh){mesh.geometry.dispose();const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const material of materials){for(const value of Object.values(material)){if(value instanceof THREE.Texture)value.dispose()}material.dispose()}}});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()}
dispose=cleanup;
const gltf=await loader.loadAsync('/avatars/mira-presenter.glb');if(cancelled){model=gltf.scene;cleanup();return}model=gltf.scene;scene.add(model);
const bones=new Map<string,import('three').Object3D>(),base=new Map<string,import('three').Euler>(),morphs:import('three').Mesh[]=[];model.traverse(object=>{const name=object.name.replace(/^mixamorig:?/,'');if((object as import('three').Bone).isBone){bones.set(name,object);base.set(name,object.rotation.clone())}const mesh=object as import('three').Mesh;if(mesh.isMesh){mesh.frustumCulled=false;if(mesh.morphTargetDictionary&&mesh.morphTargetInfluences)morphs.push(mesh);for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material]){const m=material as import('three').MeshStandardMaterial;if(m.name.includes('female_casualsuit')){m.map?.dispose();m.map=null;m.color.set('#243b5a');m.roughness=.85}if(m.name.includes('ponytail'))m.color.set('#51473d');if(m.name.includes('body')){m.color.set('#e3b49b');m.roughness=.68}if(m.name.includes('eyelashes')||m.name.includes('eyebrows')){m.side=THREE.DoubleSide;m.alphaTest=.15}}}});
// Rest posture keeps the hands near the waist; gesture offsets are applied to the existing skeletal rig.
for(const [name,sign] of [['LeftArm',1],['RightArm',-1]] as const){const bone=bones.get(name);if(bone){bone.rotation.set(1.25,sign*.18,sign*.04);base.set(name,bone.rotation.clone())}}
const morphNames=new Set(morphs.flatMap(mesh=>Object.keys(mesh.morphTargetDictionary!)));const smooth:Record<string,number>={};let last=performance.now(),alive=0,utterance=0;function pose(name:string,x=0,y=0,z=0){const bone=bones.get(name),rest=base.get(name);if(bone&&rest){bone.rotation.set(rest.x+x,rest.y+y,rest.z+z)}}
function render(now:number){if(cancelled)return;const dt=Math.min(.05,(now-last)/1000);last=now;alive+=dt;const {audio,cues}=latest.current.playback(),speaking=!!audio&&!audio.paused&&!audio.ended;utterance=speaking?audio.currentTime:0;const moving=latest.current.motion&&!document.hidden;const targets=speaking?speechWeights(cues,utterance):{};const blink=moving?blinkAt(alive):0;targets.eyeBlinkLeft=blink;targets.eyeBlinkRight=blink;targets.mouthSmileLeft=speaking?.075:.18;targets.mouthSmileRight=speaking?.075:.18;targets.browInnerUp=speaking&&moving?.035:0;
for(const name of morphNames)smooth[name]=smoothValue(smooth[name]||0,targets[name]||0,dt,name.startsWith('eyeBlink')?40:24);for(const mesh of morphs){for(const [name,index] of Object.entries(mesh.morphTargetDictionary!))mesh.morphTargetInfluences![index]=smooth[name]}
const energy=moving&&speaking?gestureAt(utterance,true):0;const gesture=smoothValue(smooth.gesture||0,energy,dt,5);smooth.gesture=gesture;const breathing=moving?Math.sin(alive*1.5)*.006:0;const nod=moving&&speaking?Math.sin(utterance*1.8)*.017:0;pose('Head',nod,moving?Math.sin(alive*.43)*.018:0,moving?Math.sin(alive*.32)*.009:0);pose('Neck',breathing*.5);pose('Spine2',breathing,0,moving?Math.sin(alive*.6)*.004:0);pose('LeftArm',-gesture*.15,gesture*.12,gesture*.06);pose('LeftForeArm',gesture*.95,0,gesture*.18);pose('LeftHand',-gesture*.14,gesture*.12,gesture*.07);if(latest.current.topic==='compare'){pose('RightArm',-gesture*.11,-gesture*.12,-gesture*.04);pose('RightForeArm',gesture*.8,0,-gesture*.15)}else{pose('RightArm');pose('RightForeArm')}model!.position.y=breathing*.15;renderer.render(scene,camera);loop=requestAnimationFrame(render)}
setStatus('ready');loop=requestAnimationFrame(render);
}catch{if(!cancelled)setStatus('fallback');dispose()}}
void initialize();return()=>{cancelled=true;dispose()}},[]);
return <div className="mira-stage" data-renderer={status} role="img" aria-label="Mira, CARWISE’s animated 3D presenter"><div className="mira-stage-light" aria-hidden="true"/><div ref={container} className="mira-canvas"/>{status!=='ready'&&<div className="mira-stage-fallback"><img src="/mira-guide.png" alt=""/><span>{status==='loading'?'Preparing Mira…':'Portrait mode · 3D unavailable'}</span></div>}<div className="mira-stage-caption"><span>MIRA</span><small>Your car-buying guide</small></div></div>
}
