import { z } from 'zod';
import { categories,featureGroups,standard,carPath, type Car, type Evidence } from './cars';
export const sourceTypes = ['manufacturer','independent','owner','expert','estimate','platform','demo'] as const;
const safeUrl=z.string().max(2048).refine(v=>v===''||/^https:\/\//i.test(v)||/^\/api\/images\/[a-zA-Z0-9-]+$/.test(v),'Use an HTTPS image URL or a CARWISE uploaded image URL');
const date=z.string().refine(s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Use a valid YYYY-MM-DD date');
const provenance={sourceType:z.enum(sourceTypes),source:z.string().max(2000),lastUpdated:date,confidence:z.enum(['high','medium','low'])};
export const numberEvidence=z.object({value:z.number().finite().nonnegative().nullable(),unit:z.string().max(40),...provenance}).strict().superRefine((v,c)=>{if(v.value!==null&&v.sourceType!=='demo'&&!v.source.trim())c.addIssue({code:z.ZodIssueCode.custom,message:'A source is required for non-demo values',path:['source']})});
const textEvidence=z.object({value:z.string().max(3000).nullable(),...provenance}).strict().superRefine((v,c)=>{if(v.value!==null&&v.sourceType!=='demo'&&!v.source.trim())c.addIssue({code:z.ZodIssueCode.custom,message:'A source is required for non-demo values',path:['source']})});
const score=z.object({score:z.number().min(0).max(10).nullable(),maxScore:z.literal(10),explanation:z.string().max(3000),positiveFactors:z.array(z.string().max(500)).max(15),negativeFactors:z.array(z.string().max(500)).max(15),sources:z.array(z.string().trim().min(1).max(2000)).max(10)}).strict().superRefine((v,c)=>{if(v.score!==null&&(!v.explanation.trim()||!v.sources.length))c.addIssue({code:'custom',path:['explanation'],message:'A supplied score needs an explanation and at least one source'});});
export const scoreKeys=['performance','comfort','safety','features','practicality','efficiency','ownership','customerFeedback','technology','value'] as const;
export const imageSchema=z.object({url:safeUrl,alt:z.string().max(300),credit:z.string().max(500),primary:z.boolean()}).strict();
export const carSchema=z.object({
 id:z.string().min(3).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,'Use lowercase letters, numbers and hyphens for the id'),
 brand:z.string().trim().min(1).max(100),model:z.string().trim().min(1).max(100),variant:z.string().trim().min(1).max(100),year:z.number().int().min(1990).max(2100),
 status:z.enum(['draft','published']),dataMode:z.enum(['demo','sourced']),bodyType:z.enum(['Hatchback','Compact SUV','SUV','Sedan','MPV','Premium SUV','EV']),fuelType:z.enum(['Petrol','Diesel','CNG','Strong Hybrid','Mild Hybrid','EV']),transmission:z.enum(['Manual','AMT','CVT','DCT','Torque Converter','e-CVT','Automatic']),
 exShowroomPrice:numberEvidence,onRoadPrice:z.record(numberEvidence),engine:textEvidence,power:numberEvidence,torque:numberEvidence,claimedMileage:numberEvidence,seating:numberEvidence,bootSpace:numberEvidence,groundClearance:numberEvidence,
 dimensions:z.object({length:numberEvidence,width:numberEvidence,height:numberEvidence,turningRadius:numberEvidence}).strict(),
 realWorldMileage:z.object({city:numberEvidence,highway:numberEvidence,mixed:numberEvidence,ownerRange:textEvidence}).strict(),
 safety:z.object({ncap:textEvidence,adultProtection:numberEvidence,childProtection:numberEvidence,safetyAssist:numberEvidence,airbags:numberEvidence,adas:textEvidence,structure:textEvidence}).strict(),
 features:z.array(z.object({name:z.string().trim().min(1).max(200),category:z.enum(['Exterior','Interior','Technology','Safety','Convenience']),status:z.enum(['standard','optional','unavailable','unknown']),availableFrom:z.string().max(200),evidence:textEvidence}).strict()).max(200),
 ownership:z.object({warranty:textEvidence,serviceInterval:textEvidence,annualMaintenance:numberEvidence,annualInsurance:numberEvidence,tyres:numberEvidence,brakes:numberEvidence,battery:numberEvidence,reliability:textEvidence}).strict(),
 customerFeedback:z.object({rating:numberEvidence,reviewCount:z.number().int().nonnegative(),summary:textEvidence,positiveThemes:z.array(z.string().max(500)).max(20),concerns:z.array(z.string().max(500)).max(20)}).strict(),
 scores:z.object(Object.fromEntries(scoreKeys.map(k=>[k,score])) as Record<typeof scoreKeys[number],typeof score>).strict(),images:z.array(imageSchema).max(12)
}).strict().superRefine((v,c)=>{
 if(v.exShowroomPrice.unit!=='INR')c.addIssue({code:'custom',path:['exShowroomPrice','unit'],message:'Price must be in INR rupees, not lakh'});
 if(v.exShowroomPrice.value!==null&&v.exShowroomPrice.value<10000)c.addIssue({code:'custom',path:['exShowroomPrice','value'],message:'Enter the full rupee price, e.g. 1643000; do not enter 16.43'});
 for(const [city,e] of Object.entries(v.onRoadPrice))if(e.unit!=='INR')c.addIssue({code:'custom',path:['onRoadPrice',city,'unit'],message:'On-road price must use INR'});
 if(v.seating.value!==null&&(!Number.isInteger(v.seating.value)||v.seating.value<1||v.seating.value>12))c.addIssue({code:'custom',path:['seating','value'],message:'Seating must be a whole number from 1 to 12'});
 if(v.customerFeedback.rating.value!==null&&(v.customerFeedback.rating.value>5||v.customerFeedback.reviewCount===0))c.addIssue({code:'custom',path:['customerFeedback','rating','value'],message:'Rating must be 0–5 with a nonzero sourced review count'});
 if(v.images.filter(i=>i.primary).length>1)c.addIssue({code:'custom',path:['images'],message:'Only one image can be primary'});
 if(v.fuelType==='EV'&&v.claimedMileage.value!==null&&v.claimedMileage.unit!=='km')c.addIssue({code:'custom',path:['claimedMileage','unit'],message:'EV claimed range uses km'});
 if(v.fuelType==='CNG'&&v.claimedMileage.value!==null&&v.claimedMileage.unit!=='km/kg')c.addIssue({code:'custom',path:['claimedMileage','unit'],message:'CNG efficiency uses km/kg'});
 if(!['EV','CNG'].includes(v.fuelType)&&v.claimedMileage.value!==null&&v.claimedMileage.unit!=='km/l')c.addIssue({code:'custom',path:['claimedMileage','unit'],message:'Liquid fuel efficiency uses km/l'});
 const names=v.features.map(f=>f.name.toLowerCase());if(new Set(names).size!==names.length)c.addIssue({code:'custom',path:['features'],message:'Feature names must be unique'});
});
export type CarData=z.infer<typeof carSchema>;
export const importSchema=z.object({schemaVersion:z.literal(1),cars:z.array(carSchema).min(1).max(100)}).strict().superRefine((v,c)=>{const ids=v.cars.map(c=>c.id);if(new Set(ids).size!==ids.length)c.addIssue({code:'custom',path:['cars'],message:'Duplicate car IDs in this import. Each ID must be unique.'});const paths=v.cars.map(x=>[x.brand,x.model,x.variant].map(s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-')).join('/'));if(new Set(paths).size!==paths.length)c.addIssue({code:'custom',path:['cars'],message:'Duplicate brand/model/variant combinations. Use one stable ID per variant.'})});
export function parseCarImport(text:string){let cleaned=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let input:unknown;try{input=JSON.parse(cleaned)}catch(e){throw new Error('Invalid JSON. Check commas, quotation marks and brackets. '+(e instanceof Error?e.message:''))}if(Array.isArray(input))input={schemaVersion:1,cars:input};else if(input&&typeof input==='object'&&'id' in input)input={schemaVersion:1,cars:[input]};const result=importSchema.safeParse(input);if(!result.success)throw new Error(result.error.issues.map(i=>`${i.path.join('.')||'root'}: ${i.message}`).join('\n'));return result.data;}
const dateToday='2026-10-03';
export function numeric(value:number|null,unit:string,sourceType:typeof sourceTypes[number]='demo',source=''):z.infer<typeof numberEvidence>{return {value,unit,sourceType,source,lastUpdated:dateToday,confidence:'low'}};
export function textual(value:string|null,sourceType:typeof sourceTypes[number]='demo',source=''):z.infer<typeof textEvidence>{return {value,sourceType,source,lastUpdated:dateToday,confidence:'low'}};
export function toCarData(c:Car):CarData{
 if(c.record)return structuredClone(c.record);
 const emptyScore={score:null,maxScore:10 as const,explanation:'Data unavailable. Add evidence before assigning a score.',positiveFactors:[],negativeFactors:[],sources:[]};
 const record:CarData={id:c.id,brand:c.brand,model:c.model,variant:c.variant,year:2026,status:'published',dataMode:'demo',bodyType:c.body as CarData['bodyType'],fuelType:c.fuel as CarData['fuelType'],transmission:c.transmission as CarData['transmission'],exShowroomPrice:numeric(c.price*100000,'INR'),onRoadPrice:{},engine:textual(c.engine),power:numeric(c.power,'PS'),torque:numeric(c.torque,'Nm'),claimedMileage:numeric(c.mileage,c.fuel==='EV'?'km':c.fuel==='CNG'?'km/kg':'km/l'),seating:numeric(c.seats,'people'),bootSpace:numeric(c.boot,'L'),groundClearance:numeric(c.clearance,'mm'),dimensions:{length:numeric(null,'mm'),width:numeric(null,'mm'),height:numeric(null,'mm'),turningRadius:numeric(null,'m')},realWorldMileage:{city:numeric(null,c.fuel==='EV'?'km/kWh':c.fuel==='CNG'?'km/kg':'km/l'),highway:numeric(null,c.fuel==='EV'?'km/kWh':c.fuel==='CNG'?'km/kg':'km/l'),mixed:numeric(null,c.fuel==='EV'?'km/kWh':c.fuel==='CNG'?'km/kg':'km/l'),ownerRange:textual(null)},safety:{ncap:textual(null),adultProtection:numeric(null,'points'),childProtection:numeric(null,'points'),safetyAssist:numeric(null,'points'),airbags:numeric(null,'count'),adas:textual(null),structure:textual(null)},features:[],ownership:{warranty:textual(null),serviceInterval:textual(null),annualMaintenance:numeric(null,'INR'),annualInsurance:numeric(null,'INR'),tyres:numeric(null,'INR'),brakes:numeric(null,'INR'),battery:numeric(null,'INR'),reliability:textual(null)},customerFeedback:{rating:numeric(null,'/5'),reviewCount:0,summary:textual(null),positiveThemes:[],concerns:[]},scores:Object.fromEntries(scoreKeys.map((k,i)=>[k,{...emptyScore,score:c.scores[i],explanation:`Illustrative ${categories[i]} assessment. Not an independently measured result.`,sources:['CARWISE demonstration dataset']}])) as unknown as CarData['scores'],images:c.image?[{url:c.image,alt:c.brand+' '+c.model,credit:'Honda · regional model imagery; equipment may differ',primary:true}]:[]};
 if(c.id==='honda-elevate-zx-cvt'){
  record.features=Object.entries(featureGroups).flatMap(([category,names])=>names.map(name=>({name,category:category as CarData['features'][number]['category'],status:standard.includes(name)?'standard' as const:'unavailable' as const,availableFrom:standard.includes(name)?'ZX · demo':'',evidence:textual(standard.includes(name)?'Listed in demo variant':'Not listed in demo variant')})));
  record.dimensions={length:numeric(4312,'mm'),width:numeric(1790,'mm'),height:numeric(1650,'mm'),turningRadius:numeric(5.2,'m')};
  record.realWorldMileage={city:numeric(11,'km/l','estimate','CARWISE demo scenario; not measured'),highway:numeric(16,'km/l','estimate','CARWISE demo scenario; not measured'),mixed:numeric(13,'km/l','estimate','CARWISE demo scenario; not measured'),ownerRange:textual(null)};
  record.ownership.warranty=textual('3 years / unlimited kilometres · demo');
  record.scores.comfort.positiveFactors=['Smooth CVT for stop-start traffic · demo assessment','Spacious cabin · demo assessment'];
  record.scores.efficiency.negativeFactors=['City fuel economy depends strongly on traffic and AC use.'];
 }
 return record;
}
export function normalizeCar(d:CarData):Car{const image=d.images.find(i=>i.primary)||d.images[0];return {id:d.id,brand:d.brand,model:d.model,variant:d.variant,price:(d.exShowroomPrice.value??0)/100000,body:d.bodyType,fuel:d.fuelType,transmission:d.transmission,power:d.power.value??0,torque:d.torque.value??0,mileage:d.claimedMileage.value??0,boot:d.bootSpace.value??0,clearance:d.groundClearance.value??0,seats:d.seating.value??0,engine:d.engine.value??'Data unavailable',scores:scoreKeys.map(k=>d.scores[k].score??0),scoreAvailable:scoreKeys.every(k=>d.scores[k].score!==null),image:image?.url||'',record:d};}
export function completeness(d:CarData){const points=[d.exShowroomPrice,d.engine,d.power,d.torque,d.claimedMileage,d.seating,d.bootSpace,d.groundClearance,d.safety.ncap,d.ownership.warranty,d.ownership.annualMaintenance,d.customerFeedback.rating];return {data:Math.round(points.filter(p=>p.value!==null).length/points.length*100),sources:Math.round(points.filter(p=>p.value!==null&&p.source.trim()&&p.sourceType!=='demo').length/points.length*100)}};
export const jsonTemplate={schemaVersion:1,cars:[(()=>{const d=toCarData({id:'your-brand-your-model-your-variant',brand:'Your brand',model:'Your model',variant:'Your variant',price:0,body:'SUV',fuel:'Petrol',transmission:'Automatic',power:0,torque:0,mileage:0,boot:0,clearance:0,seats:0,engine:'',scores:Array(10).fill(0),image:''});d.status='draft';d.dataMode='sourced';d.exShowroomPrice=numeric(null,'INR','manufacturer');d.engine=textual(null,'manufacturer');for(const key of ['power','torque','claimedMileage','seating','bootSpace','groundClearance'] as const)d[key]={...d[key],value:null,sourceType:'manufacturer'};for(const k of scoreKeys){d.scores[k].score=null;d.scores[k].sources=[];d.scores[k].explanation='Data unavailable. Add evidence before assigning a score.';}d.features=[{name:'LED headlights',category:'Exterior',status:'unknown',availableFrom:'',evidence:textual(null,'manufacturer')}];return d})()]};
export const aiImportPrompt=`Return valid JSON only using the attached CARWISE schemaVersion 1 template. Keep every field and exact key spelling. All prices are full INR rupees (1643000, not 16.43). Use null for unavailable values; never invent specifications, NCAP results, reviews or source URLs. Label each value's sourceType, source, lastUpdated (YYYY-MM-DD) and confidence. Use status "draft" until reviewed. Every category score is nullable and out of exactly 10; explain factors and sources. Use fuel-appropriate efficiency units: km/l, km/kg for CNG, km for EV range. You can return one car or {"schemaVersion":1,"cars":[...]}. HTTPS image URLs are optional; I can upload images in the admin dashboard later.`;
