import type { CarData } from './car-import';
export type Car={id:string;brand:string;model:string;variant:string;price:number;body:string;fuel:string;transmission:string;power:number;torque:number;mileage:number;boot:number;clearance:number;scores:number[];image:string;engine:string;seats:number;record?:CarData;scoreAvailable?:boolean};
export const categories=['Performance & Powertrain','Ride & Comfort','Safety & ADAS','Features & Convenience','Space & Practicality','Mileage & Efficiency','Ownership & Reliability','Customer Feedback','Technology & Connectivity','Value for Money'];
const images={elevate:'https://hondalatincaribbean.com/upload/car/elevate-2025/color/rhd-platinum-white-pearl/1.png',seltos:'https://img.autocarindia.com/mmv_images/colors/20230609124540_Kia_Seltos_Clear_White.jpg',creta:'https://img.autocarindia.com/mmv_images/colors/20240116124312_Hyundai_Creta_Atlas_White.jpg'};
const rows:any[]=[['Honda','Elevate','ZX CVT',16.43,'SUV','Petrol','CVT',121,145,16.92,458,220],['Kia','Seltos','HTX IVT',16.99,'SUV','Petrol','CVT',115,144,17.7,433,190],['Hyundai','Creta','SX(O) IVT',19.49,'SUV','Petrol','CVT',115,144,17.7,433,190],['Toyota','Urban Cruiser Hyryder','G Hybrid',19.99,'SUV','Strong Hybrid','e-CVT',116,122,27.97,265,210],['Maruti Suzuki','Grand Vitara','Zeta+ Hybrid',18.49,'SUV','Strong Hybrid','e-CVT',116,122,27.97,265,210],['Mahindra','XUV700','AX7 AT',22.99,'SUV','Diesel','Torque Converter',185,450,16,240,200],['Tata','Nexon','Creative DCA',12.49,'Compact SUV','Petrol','DCT',120,170,17.01,382,208],['Tata','Curvv','Accomplished DCA',17.49,'SUV','Petrol','DCT',125,225,15.8,500,208],['Kia','Sonet','HTX DCT',12.49,'Compact SUV','Petrol','DCT',120,172,18.4,385,205],['Hyundai','Venue','SX DCT',12.99,'Compact SUV','Petrol','DCT',120,172,18.3,350,190],['Maruti Suzuki','Brezza','ZXI AT',12.99,'Compact SUV','Petrol','Torque Converter',103,137,19.8,328,198],['Toyota','Innova Hycross','VX Hybrid',26.49,'MPV','Strong Hybrid','e-CVT',186,188,23.24,300,185],['Mahindra','Scorpio-N','Z8 AT',21.49,'SUV','Diesel','Torque Converter',175,400,15,460,187],['Mahindra','Thar','LX AT',16.49,'SUV','Diesel','Torque Converter',130,300,15,200,226],['Skoda','Kushaq','Prestige AT',18.49,'SUV','Petrol','Torque Converter',115,178,19.2,385,188],['Volkswagen','Taigun','GT DSG',18.99,'SUV','Petrol','DCT',150,250,19.01,385,188],['Honda','City','ZX CVT',16.49,'Sedan','Petrol','CVT',121,145,18.4,506,165],['Hyundai','Verna','SX IVT',15.49,'Sedan','Petrol','CVT',115,144,19.6,528,165],['MG','Astor','Sharp Pro CVT',17.49,'SUV','Petrol','CVT',110,144,14.8,448,180],['Tata','Punch EV','Empowered LR',12.99,'EV','EV','Automatic',122,190,365,366,190],['Maruti Suzuki','Swift','VXI',7.29,'Hatchback','Petrol','Manual',82,112,24.8,265,163],['Maruti Suzuki','Wagon R','LXI CNG',6.49,'Hatchback','CNG','Manual',57,82,34.05,180,165]];
export const cars:Car[]=rows.map((r,i)=>({id:(r[0]+'-'+r[1]+'-'+r[2]).toLowerCase().replace(/[^a-z0-9]+/g,'-'),brand:r[0],model:r[1],variant:r[2],price:r[3],body:r[4],fuel:r[5],transmission:r[6],power:r[7],torque:r[8],mileage:r[9],boot:r[10],clearance:r[11],scores:i===0?[9,9,8,8,9,7,9,8,9,9]:[7+i%3,8+i%2,7+i%3,8,8,6+i%4,8,7,8,7+i%3],image:i===0?images.elevate:'',engine:r[5]==='EV'?'Electric motor':i===0?'1.5L i-VTEC petrol':'Sample powertrain',seats:i===11||i===5||i===12?7:5}));
export const total=(car:Car)=>car.scores.reduce((a,b)=>a+b,0);
export const money=(n:number)=>n>=100?'₹'+(n/100).toFixed(2)+' Crore':'₹'+n.toFixed(2)+' Lakh';
export const cities:Record<string,number>={Hyderabad:1.20,Bengaluru:1.23,Mumbai:1.18,'Delhi NCR':1.16,Chennai:1.20,Pune:1.18,Kolkata:1.17};
export const featureGroups:Record<string,string[]>={Exterior:['LED headlights','LED DRLs','Fog lamps','Alloy wheels','Roof rails','Sunroof','Electric tailgate','Auto-fold ORVMs','Heated ORVMs','Rain sensing wipers'],Interior:['Automatic climate control','Rear AC vents','Ventilated seats','Heated seats','Leatherette upholstery','Electric driver seat','Memory seat','Ambient lighting','Rear sunshade','Rear armrest'],Technology:['Wireless Android Auto','Wireless Apple CarPlay','Wireless charger','Type-C ports','Digital instrument cluster','Connected car','OTA updates','Premium audio','Navigation','Voice assistant'],Safety:['Six airbags','ABS','EBD','ESC','Hill hold','Hill descent','TPMS','360° camera','LaneWatch camera','Rear camera','Parking sensors','Blind spot monitoring','Lane departure warning','Lane keep assist','Adaptive cruise control','Forward collision warning','Autonomous emergency braking','ISOFIX'],Convenience:['Cruise control','Keyless entry','Push button start','Auto headlights','Auto wipers','Rear wiper','Rear defogger','Electronic parking brake','Drive modes','60:40 rear folding seats','Rear USB charging','Cupholders']};
export const standard=['LED headlights','LED DRLs','Fog lamps','Alloy wheels','Roof rails','Sunroof','Auto-fold ORVMs','Automatic climate control','Rear AC vents','Leatherette upholstery','Rear armrest','Wireless Android Auto','Wireless Apple CarPlay','Wireless charger','Six airbags','ABS','EBD','ESC','Hill hold','LaneWatch camera','Rear camera','Parking sensors','Lane departure warning','Lane keep assist','Adaptive cruise control','Forward collision warning','Autonomous emergency braking','ISOFIX','Cruise control','Keyless entry','Push button start','Auto headlights','Rear wiper','Rear defogger','60:40 rear folding seats','Cupholders'];

export type Evidence<T>={value:T|null;unit?:string;source:string;sourceType:'manufacturer'|'independent'|'owner'|'estimate'|'platform'|'demo';lastUpdated:string;confidence:'high'|'medium'|'low'};
export const evidenceFor=(car:Car):Record<string,Evidence<unknown>>=>Object.fromEntries(Object.entries(car).filter(([k])=>!['image','id'].includes(k)).map(([key,value])=>[key,{value,source:'CARWISE demonstration dataset; requires model-year and variant verification',sourceType:key==='scores'?'platform':'demo',lastUpdated:'2026-10-03',confidence:'low'}]));

export const carPath=(c:Car)=>"/cars/"+[c.brand,c.model,c.variant].map(s=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")).join("/");
export const scoreLabel=(c:Car)=>c.scoreAvailable===false?"—":total(c);
export const mileageUnit=(c:Car)=>c.fuel==="EV"?"km":c.fuel==="CNG"?"km/kg":"km/l";
export const onRoad=(c:Car,city:string)=>c.record?.onRoadPrice[city]?.value!==null&&c.record?.onRoadPrice[city]?.value!==undefined?c.record.onRoadPrice[city].value!/100000:c.price*(cities[city]||1.2);
