import {z} from 'zod';
import {cities,categories,type Car,onRoad} from './cars';
import {scoreKeys,toCarData} from './car-import';
export const ENGINE_VERSION='carwise-local-1.0';
export const decisionInputSchema=z.object({city:z.enum(Object.keys(cities) as [string,...string[]]),budget:z.number().finite().min(100000).max(100000000),priceBasis:z.enum(['ex-showroom','on-road']),seats:z.number().int().min(1).max(9),body:z.string().max(40),fuel:z.string().max(40),transmission:z.enum(['Any','Automatic','Manual']),annualKm:z.number().finite().min(0).max(200000),cityShare:z.number().min(0).max(100),energyPrices:z.object({Petrol:z.number().positive().max(1000),Diesel:z.number().positive().max(1000),CNG:z.number().positive().max(1000),EV:z.number().positive().max(1000)}).strict(),weights:z.array(z.number().finite().min(0).max(100)).length(10).refine(w=>w.some(n=>n>0),'Give at least one priority a nonzero weight.'),requiredFeatures:z.array(z.string().trim().min(1).max(200)).max(20),requireIndependentSafety:z.boolean(),includeDemo:z.boolean(),allowEstimatedPrices:z.boolean()}).strict();
export type DecisionInput=z.infer<typeof decisionInputSchema>;
export const defaultDecisionInput:DecisionInput={city:'Hyderabad',budget:2400000,priceBasis:'on-road',seats:4,body:'Any',fuel:'Any',transmission:'Automatic',annualKm:12000,cityShare:70,energyPrices:{Petrol:105,Diesel:95,CNG:90,EV:8},weights:[10,20,20,5,10,10,10,0,5,10],requiredFeatures:[],requireIndependentSafety:false,includeDemo:true,allowEstimatedPrices:true};
export type Check={key:string;label:string;state:'pass'|'fail'|'unknown';reason:string;source:string;sourceType:string;lastUpdated:string|null};
export type Factor={key:string;label:string;weight:number;score:number|null;contribution:number|null;explanation:string;positiveFactors:string[];negativeFactors:string[];sources:string[]};
export type Decision={carId:string;status:'eligible'|'review'|'excluded';action:'shortlist'|'review_data'|'exclude';checks:Check[];factors:Factor[];score:number|null;scoreRange:[number,number];scoreCoverage:number;price:number|null;priceEstimated:boolean;annualEnergyCost:number|null;fiveYearOwnership:number|null;costNotes:string[];warnings:string[];dataMode:'demo'|'sourced'};
export type DecisionReport={engine:string;method:'transparent-rules';input:DecisionInput;generatedAt:string;decisions:Decision[];counts:{eligible:number;review:number;excluded:number};choice:{action:'compare_candidates'|'review_evidence'|'adjust_preferences';carIds:string[]};};
const round=(n:number)=>Math.round(n*10)/10;
export function decideCars(cars:Car[],raw:unknown,now=new Date()):DecisionReport{const input=decisionInputSchema.parse(raw);const total=input.weights.reduce((a,b)=>a+b,0);const decisions:Decision[]=cars.map(car=>{const d=car.record||toCarData(car);const checks:Check[]=[];const warnings:string[]=[];const add=(key:string,label:string,state:Check['state'],reason:string,evidence?:{source:string;sourceType:string;lastUpdated:string})=>checks.push({key,label,state,reason,source:evidence?.source||'CARWISE structured catalogue',sourceType:evidence?.sourceType||(d.dataMode==='demo'?'demo':'platform'),lastUpdated:evidence?.lastUpdated||null});
add('publication','Published variant',d.status==='published'?'pass':'fail',d.status==='published'?'Available in the customer catalogue.':'Draft variants cannot be recommended.');
add('demo','Data mode',d.dataMode==='demo'&&!input.includeDemo?'fail':'pass',d.dataMode==='demo'?'Illustrative demo data; verify before buying.':'Sourced record; source labels still need review.');
const officialPrice=input.priceBasis==='on-road'?d.onRoadPrice[input.city]:d.exShowroomPrice;const priceEstimated=input.priceBasis==='on-road'&&officialPrice?.value==null;const price=priceEstimated?(d.exShowroomPrice.value===null?null:onRoad(car,input.city)*100000):officialPrice?.value??null;
add('budget','Budget',price===null?'unknown':price>input.budget?'fail':priceEstimated&&!input.allowEstimatedPrices?'unknown':'pass',price===null?'Price unavailable.':price>input.budget?'Above your selected price ceiling.':priceEstimated?'Within budget using the labelled city multiplier estimate.':'Within budget using the selected catalogue price.',priceEstimated?d.exShowroomPrice:officialPrice);
add('seats','Family seating',d.seating.value===null?'unknown':d.seating.value>=input.seats?'pass':'fail',d.seating.value===null?'Seating data unavailable.':`${d.seating.value} seats; you require ${input.seats}.`,d.seating);
for(const [key,label,selected,value] of [['body','Body type',input.body,d.bodyType],['fuel','Powertrain',input.fuel,d.fuelType],['transmission','Transmission',input.transmission,d.transmission]]){const match=selected==='Any'||selected===value||(key==='transmission'&&selected==='Automatic'&&value!=='Manual');add(key,label,match?'pass':'fail',`${value}${selected==='Any'?' · no restriction':` · requested ${selected}`}`)}
if(input.requireIndependentSafety){const safety=d.safety.ncap;add('safety','Independent crash-test evidence',safety.value&&safety.sourceType==='independent'?'pass':'unknown',safety.value&&safety.sourceType==='independent'?safety.value:'No independently sourced NCAP evidence for this record. ADAS does not establish crash protection.',safety)}
for(const name of input.requiredFeatures){const f=d.features.find(f=>f.name.toLowerCase()===name.toLowerCase());add('feature:'+name,name,!f||f.status==='unknown'?'unknown':f.status==='standard'?'pass':'fail',!f||f.status==='unknown'?'Feature availability unavailable for this variant.':f.status==='standard'?`Standard on this variant. ${f.availableFrom?`Available from ${f.availableFrom}.`:''}`:f.status==='optional'?'Optional equipment does not satisfy a standard-equipment requirement.':'Not available on this variant.',f?.evidence)}
const factors:Factor[]=scoreKeys.map((key,i)=>{const s=d.scores[key];const weight=input.weights[i]/total*100;return {key,label:categories[i],weight:round(weight),score:s.score,contribution:s.score===null?null:round(weight*s.score/10),explanation:s.explanation,positiveFactors:s.positiveFactors,negativeFactors:s.negativeFactors,sources:s.sources}});
let lower=0,unknown=0;scoreKeys.forEach((key,i)=>{const w=input.weights[i]/total*100;const score=d.scores[key].score;if(score===null)unknown+=w;else lower+=w*score/10});const scoreCoverage=round(100-unknown),score=unknown>0?null:round(lower);
if(d.dataMode==='demo')warnings.push('Demo specifications and platform scores are illustrative. This is a scenario shortlist, not a verified purchase recommendation.');if(unknown>0)warnings.push('Some weighted categories lack scores. The interval assigns missing categories 0–10; no missing score is invented.');if(priceEstimated)warnings.push('On-road price uses a city multiplier, not a dealer quote.');if(!d.safety.ncap.value)warnings.push('Independent crash-test data unavailable.');
const stale=new Set(checks.filter(c=>c.lastUpdated&&now.getTime()-Date.parse(c.lastUpdated)>180*86400000).map(c=>c.label));if(stale.size)warnings.push('Evidence older than 180 days: '+[...stale].join(', ')+'.');
const eff=d.realWorldMileage;let consumption:number|null=null;const city=eff.city.value,highway=eff.highway.value,mixed=eff.mixed.value;const costNotes:string[]=[];
if(city&&highway)consumption=input.annualKm*(input.cityShare/100/city+(1-input.cityShare/100)/highway);else if(mixed){consumption=input.annualKm/mixed;costNotes.push('Mixed efficiency used; route split cannot be modelled with available data.')}else costNotes.push('Real-world efficiency unavailable. No claimed mileage is substituted.');
const energyPrice=d.fuelType==='EV'?input.energyPrices.EV:d.fuelType==='CNG'?input.energyPrices.CNG:d.fuelType==='Diesel'?input.energyPrices.Diesel:input.energyPrices.Petrol;const annualEnergyCost=consumption===null?null:Math.round(consumption*energyPrice);costNotes.push('Energy prices are editable scenario assumptions, not live city prices.');if(annualEnergyCost!==null)costNotes.push('Efficiency evidence: '+[eff.city,eff.highway,eff.mixed].filter(e=>e.value!==null).map(e=>e.sourceType+' · '+e.source).join('; '));const purchase=d.onRoadPrice[input.city]?.value??(d.exShowroomPrice.value===null?null:onRoad(car,input.city)*100000);const fiveYearOwnership=purchase!==null&&annualEnergyCost!==null&&d.ownership.annualMaintenance.value!==null&&d.ownership.annualInsurance.value!==null?Math.round(purchase+annualEnergyCost*5+d.ownership.annualMaintenance.value*5+d.ownership.annualInsurance.value*4):null;
if(fiveYearOwnership!==null)costNotes.push('On-road purchase + five years energy + five years maintenance + four insurance renewals. No financing or resale. '+(d.onRoadPrice[input.city]?.value==null?'Purchase uses a city estimate.':''));else costNotes.push('Five-year ownership unavailable: needs purchase price, real-world efficiency, maintenance and insurance.');
const status=checks.some(c=>c.state==='fail')?'excluded':checks.some(c=>c.state==='unknown')||unknown>0||d.dataMode==='demo'?'review':'eligible';return {carId:car.id,status,action:status==='excluded'?'exclude':status==='review'?'review_data':'shortlist',checks,factors,score,scoreRange:[round(lower),round(lower+unknown)],scoreCoverage,price,priceEstimated,annualEnergyCost,fiveYearOwnership,costNotes,warnings,dataMode:d.dataMode}});
const order={eligible:0,review:1,excluded:2};decisions.sort((a,b)=>order[a.status]-order[b.status]||b.scoreRange[0]-a.scoreRange[0]||a.carId.localeCompare(b.carId));const eligible=decisions.filter(d=>d.status==='eligible'),review=decisions.filter(d=>d.status==='review');return {engine:ENGINE_VERSION,method:'transparent-rules',input,generatedAt:now.toISOString(),decisions,counts:{eligible:eligible.length,review:review.length,excluded:decisions.length-eligible.length-review.length},choice:{action:eligible.length?'compare_candidates':review.length?'review_evidence':'adjust_preferences',carIds:(eligible.length?eligible:review).slice(0,5).map(d=>d.carId)}}}
