import type {Car} from './cars';
import type {DecisionReport,Decision} from './decision-engine';
export const guideTopics=['shortlist','why','tradeoffs','cost','safety','compare'] as const;
export type GuideTopic=typeof guideTopics[number];
export type Narration={title:string;paragraphs:string[];carIds:string[];topic:GuideTopic;grounding:'decision-report';supported:boolean};
const rupees=(n:number)=>Math.round(n).toLocaleString('en-IN')+' rupees';
const price=(n:number)=>n>=10000000?(n/10000000).toFixed(2)+' crore rupees':(n/100000).toFixed(2)+' lakh rupees';
const name=(c:Car)=>`${c.brand} ${c.model} ${c.variant}`;
function score(d:Decision){return d.score===null?`Its personalized score is between ${d.scoreRange[0]} and ${d.scoreRange[1]} out of 100 because some category scores are missing.`:`Its personalized score is ${d.score} out of 100.`}
function caution(d:Decision){return d.dataMode==='demo'?'These are illustrative demo specifications and scores. Treat this as a starting point and verify the exact variant before buying.':d.status==='review'?'Some evidence needs review before you decide.':'It meets your selected constraints using the supplied catalogue evidence. That is not an independent verification.'}
export function resolveGuideQuestion(question:string):GuideTopic|null{const q=question.toLowerCase().trim();if(/compare|difference|versus|\bvs\b/.test(q))return 'compare';if(/safe|safety|crash|ncap|airbag|adas/.test(q))return 'safety';if(/cost|fuel|running|ownership|expense|monthly|insurance|emi/.test(q))return 'cost';if(/trade.?off|concern|disadvantage|give up|weakness/.test(q))return 'tradeoffs';if(/why|score|rank|reason|recommend|suitable|fit/.test(q))return 'why';if(/shortlist|options|candidates|summary/.test(q))return 'shortlist';return null}
export function buildNarration(report:DecisionReport,cars:Car[],topic:GuideTopic,selectedId?:string,question?:string):Narration{const eligible=report.decisions.filter(d=>d.status!=='excluded');const chosen=report.decisions.find(d=>d.carId===selectedId)||eligible[0];const car=cars.find(c=>c.id===chosen?.carId);const result=(title:string,paragraphs:string[],ids:string[]=car?[car.id]:[]):Narration=>({title,paragraphs,carIds:ids,topic,grounding:'decision-report',supported:true});
if(question&&resolveGuideQuestion(question)===null)return {...result('Let’s keep this grounded.',["I can explain the shortlist, category scores, trade-offs, safety evidence, running costs, and differences between the first two candidates. Choose one of those topics, or ask about the selected car. I cannot research new specifications or answer unrelated questions."]),supported:false};
if(topic==='shortlist'){if(!eligible.length)return result('Let’s adjust your preferences.',[`I could not find a car within your current constraints. Your maximum ${report.input.priceBasis} budget is ${price(report.input.budget)} in ${report.input.city}. Try changing the budget, seating requirement or powertrain, then I can walk you through the results.`],[]);const first=eligible[0],firstCar=cars.find(c=>c.id===first.carId)!;return result('Let’s walk through your shortlist.',[`Hi, I’m Mira, your CARWISE guide. With your current preferences, ${report.counts.eligible} cars meet the constraints and ${report.counts.review} need evidence review.`,`${name(firstCar)} appears first in the current ranking. ${score(first)} ${caution(first)}`,`The ranking puts eligible candidates before review candidates, then sorts by the conservative weighted score. It does not mean this car is best for everyone. ${eligible.length>1?'The next options are '+eligible.slice(1,3).map(d=>name(cars.find(c=>c.id===d.carId)!)).join(' and ')+'.':''}`,"Choose a car below, and I’ll explain its reasons, trade-offs or ownership assumptions."],eligible.slice(0,3).map(d=>d.carId))}
if(!chosen||!car)return result('No car is selected.',['Adjust your preferences to find a candidate, or inspect an excluded car.'],[]);
if(topic==='why'){const pass=chosen.checks.filter(c=>c.state==='pass'&&!['publication','demo'].includes(c.key)).slice(0,4),issues=chosen.checks.filter(c=>c.state!=='pass');const strongest=chosen.factors.filter(f=>f.weight>0&&f.score!==null).sort((a,b)=>b.weight-a.weight).slice(0,2);return result('Why '+car.model+' appears.',[`${name(car)} has a decision status of ${chosen.status}. ${score(chosen)} ${caution(chosen)}`,pass.length?'It passes these checks: '+pass.map(c=>c.label.toLowerCase()+', '+c.reason).join(' '):'No positive constraint checks are available.',strongest.length?'Your most influential scored priorities are '+strongest.map(f=>f.label+', weighted at '+f.weight+' percent, with '+f.score+' out of 10').join('; ')+'.':'Your weighted category scores are unavailable.',issues.length?'Please review: '+issues.slice(0,3).map(c=>c.label+', '+c.reason).join(' '):'Every selected hard constraint has a known matching value.','The score is the sum of category scores out of ten, multiplied by your normalized weights. Unknown category scores use an interval, not a guessed value.'])}
if(topic==='tradeoffs'){const weak=chosen.factors.filter(f=>f.weight>0&&f.score!==null).sort((a,b)=>a.score!-b.score!).slice(0,2);const negatives=chosen.factors.flatMap(f=>f.negativeFactors).slice(0,3);return result('Trade-offs to consider.',[`${name(car)} deserves a closer look at what you may give up. ${caution(chosen)}`,weak.length?'Its lower scored priorities are '+weak.map(f=>`${f.label}, ${f.score} out of 10`).join(' and ')+'. These are platform assessments, not laboratory measurements.':'Category evidence is incomplete.',negatives.length?'The supplied assessment flags: '+negatives.join('; ')+'.':'No specific negative factors have been supplied. That does not mean there are no drawbacks.',...chosen.warnings.slice(0,2),"Use the full scorecard and a test drive to check these trade-offs against your needs."])}
if(topic==='cost'){const notes=chosen.costNotes;return result('The ownership picture.',[`${name(car)} has a ${report.input.priceBasis} price of ${chosen.price===null?'an unavailable amount':price(chosen.price)}${chosen.priceEstimated?', using an estimated city multiplier':''}.`,chosen.annualEnergyCost===null?'I cannot give a fuel or charging cost because real-world efficiency is unavailable. I will not substitute claimed mileage.':`At ${report.input.annualKm.toLocaleString('en-IN')} kilometres a year, estimated monthly fuel or charging cost is ${rupees(chosen.annualEnergyCost/12)}. This uses your energy prices and available real-world efficiency, with ${report.input.cityShare} percent city driving where city and highway data exist.`,chosen.fiveYearOwnership===null?'The five-year ownership total is unavailable because some required cost inputs are missing.':'The five-year ownership scenario is '+price(chosen.fiveYearOwnership)+'. It includes the on-road purchase, five years of energy and maintenance, and four insurance renewals.',notes.find(n=>n.startsWith('Mixed efficiency'))||'Energy prices are editable assumptions, not current fuel-station prices.',"Loan EMI, financing and resale value are not included in this decision engine’s ownership total. Use the ownership calculator to adjust financing assumptions."])}
if(topic==='safety'){const s=car.record?.safety;return result('What the safety evidence says.',[`${name(car)} needs safety evidence considered separately from equipment.`,s?.ncap.value&&s.ncap.sourceType==='independent'?`The catalogue lists independently sourced crash-test information: ${s.ncap.value}. Check the linked source for the tested variant and year.`:'There is no independently sourced crash-test result available for this record. I cannot infer a crash rating from the safety score or ADAS equipment.',s?.airbags.value!==null&&s?.airbags.value!==undefined?`The supplied specification lists ${s.airbags.value} airbags. This is ${s.airbags.sourceType} data.`:'Airbag specifications are unavailable in this record.',s?.adas.value?`The supplied ADAS information is: ${s.adas.value}.`:'ADAS details are unavailable in this record.','Driver assistance does not replace attention or establish crash protection. Review source labels and the exact variant before deciding.'])}
const two=eligible.slice(0,2);if(two.length<2)return result('We need two candidates to compare.',['Fewer than two cars remain in your shortlist. Broaden your constraints, then compare their evidence and trade-offs.'],two.map(d=>d.carId));const [a,b]=two;const ca=cars.find(c=>c.id===a.carId)!,cb=cars.find(c=>c.id===b.carId)!;const diffs=a.factors.map((f,i)=>({a:f,b:b.factors[i]})).filter(x=>x.a.weight>0&&x.a.score!==null&&x.b.score!==null&&x.a.score!==x.b.score).sort((x,y)=>y.a.weight-x.a.weight).slice(0,2);return result('Compare the first two candidates.',[`${name(ca)} and ${name(cb)} are the first two current candidates. This comparison uses the first two results, regardless of the selected car.`,`${ca.model}: ${score(a)} ${cb.model}: ${score(b)}`,diffs.length?'The differences in your weighted priorities include '+diffs.map(x=>`${x.a.label}: ${ca.model} scores ${x.a.score} out of ten, while ${cb.model} scores ${x.b.score}`).join('; ')+'.':'Their available weighted scores do not show a category difference, or evidence is missing.',`Prices are ${a.price===null?'unavailable':price(a.price)} for ${ca.model} and ${b.price===null?'unavailable':price(b.price)} for ${cb.model}. ${a.priceEstimated||b.priceEstimated?'At least one price is a city estimate.':''}`,a.dataMode==='demo'||b.dataMode==='demo'?'At least one candidate uses demo data. Verify current specifications and prices before buying.':'Review the original evidence before drawing conclusions.',"Open their scorecards or add them to Compare to inspect all the differences."],two.map(d=>d.carId))}
export function speechChunks(paragraphs:string[],limit=420){return paragraphs.flatMap(p=>{const words=p.trim().split(/\s+/).filter(Boolean);const chunks:string[]=[];let chunk='';for(const word of words){if(chunk&&chunk.length+word.length+1>limit){chunks.push(chunk);chunk=''}chunk+=(chunk?' ':'')+word}if(chunk)chunks.push(chunk);return chunks})}
// Web Speech does not expose gender. Match known provider voice names; unknown
// voices cannot silently become Mira's default. Local-only restriction remains.
export function isMiraFemaleVoice(voice:{name:string;lang:string;localService:boolean}){return voice.localService&&/^en(?:-|_)/i.test(voice.lang)&&(/\b(Tara|Veena|Neerja|Heera|Aditi|Diya|Meera|Aarti|Ananya|Kavya|Aashi|Lavanya|Samantha|Karen|Moira|Tessa|Fiona|Serena|Victoria|Sonia|Jenny|Aria|Ava|Emma|Michelle|Susan|Hazel|Zira|Emily|Libby|Maisie|Natasha|Clara|Catherine|Flo|Shelley|Sandy)\b/i.test(voice.name)||/\bfemale\b/i.test(voice.name))}
export function preferredVoice<T extends {lang:string;name:string;voiceURI:string;localService:boolean;default?:boolean}>(voices:T[]):T|undefined{const female=voices.filter(isMiraFemaleVoice);return female.find(v=>/^en[-_]IN$/i.test(v.lang)&&/\b(Tara|Veena|Neerja)\b/i.test(v.name))||female.find(v=>/^en[-_]IN$/i.test(v.lang))||female.find(v=>/\bSamantha\b/i.test(v.name))||female.find(v=>v.default)||female[0]}
