import {MIRA_MODEL,MIRA_VOICE,timedVisemes,encodeWav,type VisemeCue} from './mira-speech';
import {speechEnergy,type SpeechEnergy} from './mira-motion';
type Message={type:string;data:{audio?:AudioBuffer;visemes?:string[];vtimes?:number[];vdurations?:number[];error?:string}};
type Runtime={isConnected:boolean;ww:Worker|null;clear:()=>void;connect:(settings:null,progress:(event:ProgressEvent)=>void)=>Promise<void>;setup:(settings:Record<string,unknown>)=>Promise<void>;synthesize:(settings:{input:string})=>Promise<Message[]>};
export type LocalClip={wav:ArrayBuffer;cues:VisemeCue[];energy:SpeechEnergy};
export class LocalVoice{
 private runtime:Runtime|null=null;private context:AudioContext|null=null;private loading:Promise<void>|null=null;
 async load(onProgress:(message:string)=>void){if(this.runtime?.isConnected)return;if(this.loading)return this.loading;this.loading=this.initialize(onProgress).finally(()=>{this.loading=null});return this.loading}
 private async initialize(onProgress:(message:string)=>void){onProgress('Preparing Mira’s local voice…');const url=new URL('/vendor/headtts/headtts.mjs',window.location.origin).href;const {HeadTTS}=await import(/* @vite-ignore */ url);this.context=new AudioContext();this.runtime=new HeadTTS({endpoints:['wasm'],audioCtx:this.context,workerModule:new URL('/vendor/headtts/worker-tts.mjs',window.location.origin).href,transformersModule:'https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.0.0/dist/transformers.min.js',model:MIRA_MODEL,dtypeWasm:'q8',dictionaryURL:new URL('/vendor/headtts/dictionaries/',window.location.origin).href,voices:[MIRA_VOICE],defaultVoice:MIRA_VOICE,defaultLanguage:'en-us',splitSentences:false,splitLength:350,trace:0}) as Runtime;await this.runtime.connect(null,event=>{onProgress(event.lengthComputable?`Loading voice · ${Math.round(event.loaded/event.total*100)}% (${Math.round(event.loaded/1000000)} MB)`:'Loading voice…')});if(!this.runtime.isConnected)throw new Error('The local model could not load. Check your connection, then retry.');onProgress('Local voice ready')}
 async generate(text:string,speed:number):Promise<LocalClip>{if(!this.runtime?.isConnected)throw new Error('Load the voice first.');await this.runtime.setup({voice:MIRA_VOICE,language:'en-us',speed,audioEncoding:'wav'});const messages=await this.runtime.synthesize({input:text});const message=messages.find(m=>m.type==='audio');if(!message?.data.audio)throw new Error('Could not generate local speech. Retry on a device with more available memory.');const d=message.data;return {energy:speechEnergy(d.audio!.getChannelData(0),d.audio!.sampleRate),wav:encodeWav(d.audio!.getChannelData(0),d.audio!.sampleRate),cues:timedVisemes(d.visemes||[],d.vtimes||[],d.vdurations||[])}}
 clear(){this.runtime?.clear()}
 dispose(){this.runtime?.clear();this.runtime?.ww?.terminate();this.runtime=null;void this.context?.close();this.context=null}
}
