export const MIRA_VOICE='af_heart';
export const MIRA_MODEL='onnx-community/Kokoro-82M-v1.0-ONNX-timestamped';
export type MiraEmotion='auto'|'neutral'|'cheerful'|'empathetic';
export type VisemeCue={seconds:number;duration:number;frame:number};
export function deliveryFor(topic:string,emotion:MiraEmotion,rate=1){const delivery=emotion==='auto'?(['safety','tradeoffs'].includes(topic)?'empathetic':'neutral'):emotion;return {delivery,speed:Math.min(1.2,Math.max(.75,rate*(delivery==='empathetic'?.93:delivery==='cheerful'?1.04:.98))),pause:delivery==='empathetic'?380:delivery==='cheerful'?180:260}}
export function mouthFrame(viseme:string){if(['sil','PP'].includes(viseme))return 0;if(viseme==='aa')return 1;if(viseme==='O')return 3;if(['U','W'].includes(viseme))return 4;if(viseme==='FF')return 5;return 2}
export function cueAt(cues:VisemeCue[],seconds:number){let lo=0,hi=cues.length-1,answer:VisemeCue|undefined;while(lo<=hi){const mid=(lo+hi)>>1;if(cues[mid].seconds<=seconds){answer=cues[mid];lo=mid+1}else hi=mid-1}return answer&&seconds<answer.seconds+answer.duration?answer.frame:0}
export function normalizeSpeech(text:string){return text.replace(/₹\s*([\d,.]+)\s*(Lakh|Crore)/gi,(_,n,unit)=>n.replace(/,/g,'')+' '+unit.toLowerCase()+' rupees').replace(/₹\s*([\d,.]+)/g,(_,n)=>n.replace(/,/g,'')+' rupees').replace(/\bkm\/l\b/gi,'kilometres per litre').replace(/\bkWh\b/g,'kilowatt hours').replace(/\bCVT\b/g,'C V T').replace(/\bADAS\b/g,'A D A S').replace(/(\d)\/(\d)/g,'$1 out of $2')}
export function timedVisemes(visemes:string[],times:number[],durations:number[]):VisemeCue[]{return visemes.map((v,i)=>({seconds:Math.max(0,times[i]/1000),duration:Math.max(0,durations[i]/1000),frame:mouthFrame(v)})).filter(c=>Number.isFinite(c.seconds)&&Number.isFinite(c.duration)).sort((a,b)=>a.seconds-b.seconds)}
export function encodeWav(samples:Float32Array,sampleRate:number){const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);function str(at:number,s:string){for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i))}str(0,'RIFF');view.setUint32(4,36+samples.length*2,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,samples.length*2,true);samples.forEach((s,i)=>view.setInt16(44+i*2,Math.round(Math.max(-1,Math.min(1,s))*(s<0?32768:32767)),true));return buffer}
