import {domainConfig,suggestScore,suggestMoney,type Domain,type SuggestRecord} from './suggest-catalogue';
import {resolveGuideQuestion,type GuideTopic,type Narration} from './guide-narration';
export function scenarioNarration(domain:Domain,records:SuggestRecord[],weights:number[],topic:GuideTopic,selected?:string,question?:string,context=''):Narration{
const config=domainConfig[domain],record=records.find(r=>r.id===selected)||records[0];const total=weights.reduce((a,b)=>a+b,0);const evidence=record?.dataMode==='sourced'?'This profile uses supplied source references. Scores remain platform assessments; supplied sources do not establish independent verification.':'These are illustrative demo scenarios. Prices, category assessments and attributes are not verified listings or independent reviews.';
const title=(t:string,paragraphs:string[],ids=record?[record.id]:[]):Narration=>({title:t,paragraphs,carIds:ids,topic,grounding:'scenario-report',supported:true});
let intent=topic;
if(question){const q=question.toLowerCase();if(/season|summer|winter|autumn|spring|weather/.test(q))intent='efficiency';else if(/legal|rera|title|approv|accredit|placement|admission|eligib|safe|verify|evidence/.test(q))intent='safety';else if(/fee|tuition|budget|price|cost|rent|purchase/.test(q))intent='cost';else if(/course|campus|bedroom|amenit|cuisine|menu|room|feature/.test(q))intent='features';else if(resolveGuideQuestion(q)===null)return {...title('What I can explain.',[`I can explain ${config.title.toLowerCase()}, the current shortlist, category scores, budgets, trade-offs, attributes and missing evidence. I cannot confirm live availability, legal status, admissions or current reviews.`]),supported:false};else intent=resolveGuideQuestion(q)!;}
if(!record)return title('Let’s widen your search.',[`No ${config.title.toLowerCase()} options match the current filters. Change the type, location or budget and I can explain the updated results.`],[]);
const factors=config.criteria.map((name,i)=>({name,score:record.scores[i],weight:Math.round(weights[i]/total*100)}));
const verification=domain==='homes'?'Legal title, sale availability, RERA registration, approvals and total transaction costs are not verified. Check the relevant official records and property documents before committing.':domain==='education'?'Accreditation, affiliation, admissions, eligibility and placement outcomes are unavailable. Verify these with the institution and relevant official authorities.':'Opening hours, current weather, seasonal access, booking availability and customer reviews are unavailable. Check current conditions and business information before making plans.';
if(intent==='shortlist')return title(domain==='homes'?'Your home shortlist.':domain==='education'?'Your education shortlist.':'Your travel and dining shortlist.',[`Hi, I’m Mira, your SuggestWise guide. You have ${records.length} options ${domain==='travel'?'across India':'in Hyderabad'} in the current scenario. ${context}`,`${records[0].name} appears first with a personalized ${records[0].dataMode==='demo'?'demo':'platform'} score of ${suggestScore(records[0],weights)} out of one hundred. ${evidence}`,records.length>1?'The next options are '+records.slice(1,3).map(r=>r.name).join(' and ')+'.':'Only one option remains.',`Ranking uses five category assessments and your normalized priorities. It does not mean the first option is right for everyone. ${verification}`],records.slice(0,3).map(r=>r.id));
if(intent==='cost')return title('Budget and price assumptions.',[`${record.name}: ${suggestMoney(record.price)}. ${record.priceLabel}. ${evidence}`,domain==='homes'?'This purchase scenario does not include verified stamp duty, registration, maintenance, loan interest or other transaction charges.':domain==='education'?'This illustrative annual tuition does not include verified accommodation, transport, deposits or other institutional fees.':`This amount is a ${record.kind==='Restaurant'?'meal-for-two':record.kind==='Hotel'?'nightly-stay':'trip-budget'} scenario. Compare only matching units. Taxes, transport and availability are not verified.`,verification]);
if(intent==='safety')return title('Evidence to verify.',[`The catalogue provides no independent verification of ${record.name}.`,verification,'A platform assessment is not legal clearance, accreditation or a safety certification. Missing evidence stays unavailable.']);
if(intent==='compare'){const two=records.slice(0,2);if(two.length<2)return title('We need two options.',['Widen your filters to compare at least two candidates.']);return title('Compare the first two.',[`${two[0].name} and ${two[1].name} are the first two current results.`,...two.map(r=>`${r.name}: personalized ${r.dataMode==='demo'?'demo':'platform'} score ${suggestScore(r,weights)} out of one hundred. ${suggestMoney(r.price)}, ${r.priceLabel}.`),config.criteria.map((c,i)=>`${c}: ${two[0].scores[i]} versus ${two[1].scores[i]} out of ten`).join('. ')+'.',evidence],two.map(r=>r.id));}
if(intent==='features'||intent==='comfort')return title('The profile and practical fit.',[`${record.name}, ${record.kind}, ${record.location}. ${evidence}`,Object.entries(record.attributes).map(([k,v])=>k+': '+v).join('. ')+'.',verification]);
if(intent==='efficiency')return title(domain==='travel'?'Season and travel fit.':'Everyday suitability.',[`${record.name}. ${evidence}`,domain==='travel'?record.seasons.length?'The demo profile includes these planning seasons: '+record.seasons.join(', ')+'. This is not a live weather forecast or verified seasonal recommendation.':'Season information is unavailable.':Object.entries(record.attributes).map(([k,v])=>k+': '+v).join('. ')+'.',verification]);
if(intent==='tradeoffs'){const low=[...factors].sort((a,b)=>a.score-b.score).slice(0,2);return title('Trade-offs to consider.',[`${record.name}. ${evidence}`,'The lowest demo assessments are '+low.map(f=>`${f.name}, ${f.score} out of ten`).join(' and ')+'. Use these to decide what to investigate, not as verified weaknesses.',verification]);}
return title('Why this option appears.',[`${record.name} receives a personalized ${record.dataMode==='demo'?'demo':'platform'} score of ${suggestScore(record,weights)} out of one hundred. ${evidence}`,...factors.filter(f=>f.weight>0).map(f=>`${f.name}: ${f.score} out of ten, weighted at ${f.weight} percent. This is an illustrative assessment.`),'The score adds each category score divided by ten, multiplied by its normalized weight. '+verification]);
}
