'use client';
import {useEffect,useState,useRef} from 'react';
import {suggestRecords,type SuggestRecord} from './suggest-catalogue';
import type {StoreSnapshot,StoreItem} from './suggest-store-schema';
type Cached={version:string;hash:string;snapshot:StoreSnapshot;updatedAt:string|null};
let memory:Cached|undefined;
async function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('suggestwise-store-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('snapshots');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function read(){try{const d=await db();return await new Promise<Cached|undefined>((resolve,reject)=>{const r=d.transaction('snapshots').objectStore('snapshots').get('published');r.onsuccess=()=>{d.close();resolve(r.result)};r.onerror=()=>{d.close();reject(r.error)}})}catch{return undefined}}
async function write(value:Cached){try{const d=await db();await new Promise<void>((resolve,reject)=>{const t=d.transaction('snapshots','readwrite');t.objectStore('snapshots').put(value,'published');t.oncomplete=()=>{d.close();resolve()};t.onerror=()=>{d.close();reject(t.error)}})}catch{/* cache is disposable; server publication remains authoritative */}}
async function refreshStore(){const cached=memory||await read();try{const response=await fetch('/api/store'+(cached?'?since='+encodeURIComponent(cached.version):''),{headers:cached?{'If-None-Match':'"'+cached.hash+'"'}:{},cache:'no-cache'});if(response.status===304&&cached){memory=cached;return {...cached,offline:false}}if(!response.ok)throw new Error('Published catalogue unavailable');const data=await response.json() as Cached & {baseVersion?:string;delta?:{removed:string[];upserts:StoreItem[]}};if(data.delta){if(!cached||data.baseVersion!==cached.version)throw new Error('Cache revision mismatch');const items=new Map(cached.snapshot.items.map(i=>[i.id,i]));for(const id of data.delta.removed)items.delete(id);for(const item of data.delta.upserts as StoreItem[])items.set(item.id,item);data.snapshot={schemaVersion:1,items:[...items.values()]};}const value:Cached={version:data.version,hash:data.hash,updatedAt:data.updatedAt,snapshot:data.snapshot};memory=value;await write(value);return {...value,offline:false};}catch(error){if(cached)return {...cached,offline:true};throw error}}
export function usePublishedScenarios(){const hash=useRef('');const [records,setRecords]=useState(suggestRecords),[notice,setNotice]=useState(''),[version,setVersion]=useState('legacy');useEffect(()=>{let alive=true;async function refresh(){try{const data=await loadStore();if(alive){if(hash.current!==data.hash){hash.current=data.hash;setRecords(data.snapshot.items.filter(i=>i.domain!=='cars').map(i=>i.data as SuggestRecord));setVersion(data.version);}setNotice(data.offline?'Offline · using the last downloaded catalogue.':'')}}catch{if(alive)setNotice('Shared catalogue unavailable · showing bundled demo profiles.')}}void refresh();const interval=setInterval(refresh,60000);window.addEventListener('online',refresh);return()=>{alive=false;clearInterval(interval);window.removeEventListener('online',refresh)}},[]);return {records,notice,version};}

let pending:ReturnType<typeof refreshStore>|undefined;
export function loadStore(){if(!pending)pending=refreshStore().finally(()=>{pending=undefined});return pending;}
