import {z} from 'zod';
import {carSchema,type CarData} from './car-import';
import {type SuggestRecord,domainConfig} from './suggest-catalogue';
export const scenarioSchema=z.object({id:z.string().regex(/^[a-z0-9-]{1,120}$/),domain:z.enum(['travel','homes','education']),name:z.string().trim().min(1).max(200),kind:z.string().max(60),location:z.string().max(120),city:z.string().max(120).optional(),region:z.string().max(120),seasons:z.array(z.enum(['Summer','Winter','Autumn','Spring'])).max(4),price:z.number().finite().min(0).max(1e10),priceLabel:z.string().max(200),summary:z.string().max(3000),attributes:z.record(z.string().max(100),z.string().max(500)),scores:z.array(z.number().min(0).max(10)).length(5),dataMode:z.enum(['demo','sourced']),sourceType:z.enum(['estimate','manufacturer','independent','expert','owner','platform']),lastUpdated:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),sources:z.array(z.object({url:z.string().url().refine(v=>v.startsWith('https://')),label:z.string().min(1).max(200),type:z.enum(['official','independent','owner','expert','estimate','platform'])}).strict()).max(20).default([]),images:z.array(z.object({url:z.string().refine(v=>v.startsWith('/api/images/')||v.startsWith('https://')),alt:z.string().min(1).max(300)}).strict()).max(12).default([]),status:z.enum(['draft','published']).default('draft')}).strict().superRefine((v,c)=>{if(!(domainConfig[v.domain].kinds as readonly string[]).includes(v.kind))c.addIssue({code:'custom',path:['kind'],message:'Invalid type for this category'});if(v.domain!=='travel'&&v.city?.toLowerCase()!=='hyderabad')c.addIssue({code:'custom',path:['city'],message:'Homes and education currently support Hyderabad only'});if(v.dataMode==='sourced'&&!v.sources.length)c.addIssue({code:'custom',path:['sources'],message:'Sourced records require evidence links'});});
export type StoreItem={id:string;domain:'cars'|'travel'|'homes'|'education';status:'draft'|'published';data:CarData|SuggestRecord;revision:number};
export type StoreSnapshot={schemaVersion:1;items:StoreItem[]};
export function validateItem(input:unknown):Omit<StoreItem,'revision'>{const envelope=z.object({domain:z.enum(['cars','travel','homes','education']),data:z.unknown()}).strict().parse(input);const data=envelope.domain==='cars'?carSchema.parse(envelope.data):scenarioSchema.parse(envelope.data);if(envelope.domain!=='cars'&&'domain' in data&&data.domain!==envelope.domain)throw new Error('Category mismatch');return {id:data.id,domain:envelope.domain,status:data.status,data:data as CarData|SuggestRecord};}
export function publicSnapshot(items:StoreItem[]):StoreSnapshot{return {schemaVersion:1,items:items.filter(i=>i.status==='published').sort((a,b)=>a.id.localeCompare(b.id))};}
export function snapshotDelta(previous:StoreSnapshot,current:StoreSnapshot){const old=new Map(previous.items.map(i=>[i.id,JSON.stringify(i)])),ids=new Set(current.items.map(i=>i.id));return {upserts:current.items.filter(i=>old.get(i.id)!==JSON.stringify(i)),removed:previous.items.filter(i=>!ids.has(i.id)).map(i=>i.id)};}
export async function contentHash(bytes:BufferSource){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');}
