export type Domain='travel'|'homes'|'education';
export type SuggestRecord={id:string;domain:Domain;name:string;kind:string;location:string;city?:string;region:string;seasons:string[];price:number;priceLabel:string;summary:string;attributes:Record<string,string>;scores:number[];dataMode:'demo'|'sourced';sourceType:'estimate'|'manufacturer'|'independent'|'expert'|'owner'|'platform';lastUpdated:string;sources?:{url:string;label:string;type:string}[];images?:{url:string;alt:string}[];status?:'draft'|'published'};
export const domainConfig={travel:{title:'Travel, dining & stays',scope:'Across India',intro:'Find a destination, a place to stay, or a table worth planning around.',criteria:['Season fit','Experience','Access','Value','Practicality'],kinds:['Destination','Restaurant','Hotel'],priceUnit:'Trip / meal / night'},homes:{title:'Find a home in Hyderabad',scope:'Hyderabad only',intro:'Compare apartments, villas and independent homes around the life you want.',criteria:['Location fit','Space','Connectivity','Amenities','Value'],kinds:['Apartment','Villa','Independent home'],priceUnit:'Purchase price'},education:{title:'Plan your next chapter',scope:'Hyderabad only',intro:'Explore colleges and universities by your course, priorities and budget.',criteria:['Course fit','Learning environment','Access','Facilities','Affordability'],kinds:['College','University'],priceUnit:'Annual fee'}} as const;
const make=(domain:Domain,name:string,kind:string,location:string,region:string,price:number,scores:number[],attributes:Record<string,string>,seasons:string[]=[]):SuggestRecord=>({id:domain+'-'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-'),domain,name,kind,location,city:domain!=='travel'?'Hyderabad':undefined,region,price,priceLabel:domain==='homes'?'Indicative purchase scenario':domain==='education'?'Illustrative annual tuition':kind==='Hotel'?'Illustrative nightly budget':kind==='Restaurant'?'Illustrative meal for two':'Illustrative trip budget',scores,attributes,seasons,summary:domain==='homes'?'A sample property profile for comparing everyday living needs.':domain==='education'?'A sample institution profile to demonstrate course and campus comparisons.':'A sample travel profile for planning around your preferences.',dataMode:'demo',sourceType:'estimate',lastUpdated:'2026-10-04'});
export const suggestRecords:SuggestRecord[]=[
make('travel','Himalayan summer escape','Destination','Mountain circuit','North India',25000,[9,8,6,7,7],{'Trip style':'Nature','Duration':'5 days','Best-fit scenario':'Cool-weather break'},['Summer','Spring']),
make('travel','Coastal winter break','Destination','Coastal circuit','South India',18000,[9,8,8,8,8],{'Trip style':'Beach','Duration':'4 days','Best-fit scenario':'Relaxed holiday'},['Winter','Autumn']),
make('travel','Heritage city trail','Destination','Heritage circuit','West India',16000,[8,9,8,8,7],{'Trip style':'Culture','Duration':'3 days','Best-fit scenario':'History & food'},['Winter','Autumn']),
make('travel','Spring garden journey','Destination','Garden circuit','North India',28000,[9,9,6,6,7],{'Trip style':'Nature','Duration':'5 days','Best-fit scenario':'Scenic itinerary'},['Spring']),
make('travel','Monsoon-to-autumn hills','Destination','Hill circuit','East India',22000,[8,8,6,7,7],{'Trip style':'Nature','Duration':'4 days','Best-fit scenario':'Slow travel'},['Autumn']),
make('travel','Deccan Table · demo','Restaurant','Hyderabad','South India',1800,[8,9,9,8,8],{'Cuisine':'Regional Indian','Dining style':'Casual','Dietary profile':'Mixed menu'},['Summer','Winter','Autumn','Spring']),
make('travel','Coastal Kitchen · demo','Restaurant','Chennai','South India',1400,[8,8,8,9,8],{'Cuisine':'South Indian','Dining style':'Casual','Dietary profile':'Vegetarian options'},['Summer','Winter','Autumn','Spring']),
make('travel','Courtyard Stay · demo','Hotel','Jaipur','North India',5500,[9,9,8,7,8],{'Stay style':'Boutique','Trip style':'Culture','Room scenario':'Double room'},['Winter','Autumn']),
make('travel','Hillview Lodge · demo','Hotel','Hill circuit','North India',4500,[9,8,6,8,7],{'Stay style':'Nature retreat','Trip style':'Nature','Room scenario':'Double room'},['Summer','Spring']),
make('homes','West Hyderabad apartment · demo','Apartment','Gachibowli','Hyderabad',12500000,[9,8,9,8,7],{'Bedrooms':'3 BHK','Area':'1,850 sq ft','Stage':'Ready-to-move scenario','Legal / RERA':'Not verified'}),
make('homes','North Hyderabad villa · demo','Villa','Kompally','Hyderabad',22000000,[7,10,7,9,7],{'Bedrooms':'4 BHK','Area':'3,200 sq ft','Stage':'Construction scenario','Legal / RERA':'Not verified'}),
make('homes','East Hyderabad apartment · demo','Apartment','Uppal','Hyderabad',7500000,[8,8,9,7,9],{'Bedrooms':'3 BHK','Area':'1,500 sq ft','Stage':'Ready-to-move scenario','Legal / RERA':'Not verified'}),
make('homes','Central city residence · demo','Independent home','Begumpet','Hyderabad',18000000,[9,8,9,6,6],{'Bedrooms':'3 BHK','Area':'2,200 sq ft','Stage':'Resale scenario','Legal / RERA':'Not verified'}),
make('homes','South Hyderabad villa · demo','Villa','Shamshabad','Hyderabad',16000000,[6,9,7,8,8],{'Bedrooms':'3 BHK','Area':'2,600 sq ft','Stage':'Construction scenario','Legal / RERA':'Not verified'}),
make('education','Engineering college · demo','College','West Hyderabad','Hyderabad',180000,[9,8,7,8,7],{'Course':'Engineering','Campus':'Day scholar scenario','Accreditation':'Not verified','Placements':'Data unavailable'}),
make('education','Business university · demo','University','North Hyderabad','Hyderabad',250000,[9,9,6,9,6],{'Course':'Management','Campus':'Residential scenario','Accreditation':'Not verified','Placements':'Data unavailable'}),
make('education','Arts & science college · demo','College','Central Hyderabad','Hyderabad',65000,[8,8,9,7,9],{'Course':'Arts & Science','Campus':'Day scholar scenario','Accreditation':'Not verified','Placements':'Data unavailable'}),
make('education','Technology university · demo','University','East Hyderabad','Hyderabad',150000,[9,8,8,9,8],{'Course':'Engineering','Campus':'Residential scenario','Accreditation':'Not verified','Placements':'Data unavailable'}),
make('education','Design college · demo','College','South Hyderabad','Hyderabad',200000,[9,9,6,8,7],{'Course':'Design','Campus':'Day scholar scenario','Accreditation':'Not verified','Placements':'Data unavailable'})];
export function suggestScore(r:SuggestRecord,weights:number[]){const total=weights.reduce((a,b)=>a+b,0);return total?Math.round(r.scores.reduce((sum,s,i)=>sum+s*(weights[i]||0),0)/total*10):null}
export function suggestMoney(value:number){return value>=10000000?'₹'+(value/10000000).toFixed(2)+' Crore':value>=100000?'₹'+(value/100000).toFixed(2)+' Lakh':'₹'+value.toLocaleString('en-IN')}
