import {database} from './catalogue-server';
import {cars} from './cars';
import {toCarData} from './car-import';
import {suggestRecords} from './suggest-catalogue';
import {publicSnapshot,contentHash,type StoreItem,type StoreSnapshot} from './suggest-store-schema';
import {ApiError} from './admin-auth';
async function baselineItems():Promise<StoreItem[]>{const db=database();const items=new Map<string,StoreItem>(cars.map(c=>{const data=toCarData(c);return [c.id,{id:c.id,domain:'cars',status:data.status,data,revision:0}]}));for(const data of suggestRecords)items.set(data.id,{id:data.id,domain:data.domain,status:'published',data,revision:0});const legacy=await db.prepare('SELECT data_json FROM catalogue').all<{data_json:string}>();for(const row of legacy.results){const data=JSON.parse(row.data_json);items.set(data.id,{id:data.id,domain:'cars',status:data.status,data,revision:0})}return [...items.values()];}
export async function workingItems():Promise<StoreItem[]>{const db=database(),items=new Map((await baselineItems()).map(i=>[i.id,i]));const stored=await db.prepare('SELECT * FROM store_records').all<{id:string;domain:StoreItem['domain'];data_json:string;status:StoreItem['status'];revision:number}>();for(const row of stored.results)items.set(row.id,{id:row.id,domain:row.domain,status:row.status,data:JSON.parse(row.data_json),revision:row.revision});return [...items.values()];}
export async function publishedStore(){const row=await database().prepare('SELECT r.id,r.data_json,r.content_hash,r.created_at FROM store_head h JOIN store_releases r ON r.id=h.release_id WHERE h.id=?').bind('published').first<{id:string;data_json:string;content_hash:string;created_at:string}>();if(row)return {version:row.id,hash:row.content_hash,updatedAt:row.created_at,snapshot:JSON.parse(row.data_json) as StoreSnapshot};const snapshot=publicSnapshot(await baselineItems());return {version:'legacy',hash:await contentHash(new TextEncoder().encode(JSON.stringify(snapshot))),updatedAt:null,snapshot};}
export async function saveItems(items:Omit<StoreItem,'revision'>[],owner:string){const current=await workingItems(),map=new Map(current.map(i=>[i.id,i])),now=new Date().toISOString(),db=database();const statements=[];for(const item of items){const previous=map.get(item.id);if(previous&&previous.domain!==item.domain)throw new ApiError('An ID cannot change category.',409);const revision=(previous?.revision||0)+1,json=JSON.stringify(item.data);if(previous&&previous.revision===0)statements.push(db.prepare('INSERT INTO store_revisions(id,record_id,revision,data_json,updated_at,updated_by) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),item.id,0,JSON.stringify(previous.data),now,'legacy catalogue'));statements.push(db.prepare('INSERT INTO store_records (id,domain,data_json,status,revision,updated_at,updated_by) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data_json=excluded.data_json,status=excluded.status,revision=excluded.revision,updated_at=excluded.updated_at,updated_by=excluded.updated_by').bind(item.id,item.domain,json,item.status,revision,now,owner));statements.push(db.prepare('INSERT INTO store_revisions (id,record_id,revision,data_json,updated_at,updated_by) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),item.id,revision,json,now,owner));}await db.batch(statements);}
export async function publishStore(owner:string,expected:string,rollbackId?:string){const previous=await publishedStore();if(previous.version!==expected)throw new ApiError('The published catalogue changed. Refresh and review it before publishing.',409);let snapshot:StoreSnapshot;if(rollbackId){const old=await database().prepare('SELECT data_json FROM store_releases WHERE id=?').bind(rollbackId).first<{data_json:string}>();if(!old)throw new ApiError('Version not found.',404);snapshot=JSON.parse(old.data_json)}else snapshot=publicSnapshot(await workingItems());const json=JSON.stringify(snapshot);if(new TextEncoder().encode(json).length>1500000)throw new ApiError('This catalogue exceeds the 1.5 MB snapshot limit. Split storage before publishing.',413);const id=crypto.randomUUID(),hash=await contentHash(new TextEncoder().encode(json)),db=database(),now=new Date().toISOString();const statements=[];if(previous.version==='legacy')statements.push(db.prepare('INSERT INTO store_releases(id,parent_id,data_json,content_hash,created_at,created_by,reason) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind('legacy',null,JSON.stringify(previous.snapshot),previous.hash,now,owner,'Original catalogue imported'));const result=await db.batch([...statements,db.prepare('INSERT INTO store_releases(id,parent_id,data_json,content_hash,created_at,created_by,reason) VALUES (?,?,?,?,?,?,?)').bind(id,previous.version,json,hash,now,owner,rollbackId?'Rollback of '+rollbackId:'Published workspace'),db.prepare("INSERT INTO store_head(id,release_id) VALUES ('published',?) ON CONFLICT(id) DO UPDATE SET release_id=excluded.release_id WHERE store_head.release_id=?").bind(id,previous.version)]);if(!result[result.length-1].meta.changes)throw new ApiError('Another publication won the race. Refresh before trying again.',409);return id;}
