import {requirePrivateOwner,ApiError,apiError} from '@/lib/admin-auth';
import {authRecord,decryptSecret,encryptSecret,newSecret,hasAdminSession,issueSession,sessionCookie} from '@/lib/admin-security';
import {verifyTotp,hashToken} from '@/lib/totp';
import {database} from '@/lib/catalogue-server';
import {cookies} from 'next/headers';
export const dynamic='force-dynamic';
function json(data:unknown,headers:Record<string,string>={}){return Response.json(data,{headers:{'Cache-Control':'no-store',...headers}})}
export async function GET(request:Request){try{const user=await requirePrivateOwner(request);const record=await authRecord();if(record&&record.owner_id!==user.userId)throw new ApiError('Only the enrolled administrator may access this workspace.',403);return json({enabled:!!record?.enabled,authenticated:await hasAdminSession(user.userId)})}catch(e){return apiError(e)}}
export async function POST(request:Request){try{const user=await requirePrivateOwner(request);if(Number(request.headers.get('content-length'))>1024)throw new ApiError('Request is too large.',413);const {action,code}=await request.json() as {action:string;code?:string};const db=database();let record=await authRecord();if(record&&record.owner_id!==user.userId)throw new ApiError('Only the enrolled administrator may access this workspace.',403);
if(action==='logout'){const token=(await cookies()).get(sessionCookie)?.value;if(token)await db.prepare('DELETE FROM admin_sessions WHERE token_hash=?').bind(await hashToken(token)).run();return json({ok:true},{'Set-Cookie':`${sessionCookie}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${new URL(request.url).protocol==='https:'?'; Secure':''}`})}
if(action==='setup'){if(record?.enabled)throw new ApiError('Authenticator is already configured.',409);let secret:string;if(record&&record.pending_until>Date.now())secret=await decryptSecret(record.secret);else{secret=newSecret();const encrypted=await encryptSecret(secret);if(!record)await db.prepare("INSERT OR IGNORE INTO admin_auth(id,owner_id,secret,enabled,pending_until,last_counter,attempts,attempt_until) VALUES('primary',?,?,0,?,-1,0,0)").bind(user.userId,encrypted,Date.now()+600000).run();else await db.prepare("UPDATE admin_auth SET secret=?,pending_until=? WHERE id='primary' AND enabled=0 AND owner_id=?").bind(encrypted,Date.now()+600000,user.userId).run();record=await authRecord();if(!record||record.enabled||record.owner_id!==user.userId)throw new ApiError('Another administrator has started enrollment.',409);secret=await decryptSecret(record.secret)}return json({secret,expiresAt:record!.pending_until})}
if(action!=='verify')throw new ApiError('Unknown authentication action.',400);if(!record)throw new ApiError('Set up Google Authenticator first.',400);if(!record.enabled&&record.pending_until<Date.now())throw new ApiError('Setup expired. Start setup again.',400);if(typeof code!=='string'||!/^\d{6}$/.test(code))throw new ApiError('Enter a six-digit code.',400);
const attempt=await db.prepare("UPDATE admin_auth SET attempts=CASE WHEN attempt_until<=? THEN 1 ELSE attempts+1 END, attempt_until=CASE WHEN attempt_until<=? THEN ? ELSE attempt_until END WHERE id='primary' AND (attempt_until<=? OR attempts<5)").bind(Date.now(),Date.now(),Date.now()+300000,Date.now()).run();if(!attempt.meta.changes)throw new ApiError('Too many attempts. Wait five minutes before trying again.',429);
const counter=await verifyTotp(await decryptSecret(record.secret),code,record.last_counter);if(counter===null)throw new ApiError('Code is incorrect, expired or already used. Try the next code and check your phone’s time.',401);
const accepted=await db.prepare("UPDATE admin_auth SET enabled=1,last_counter=? WHERE id='primary' AND owner_id=? AND last_counter<? AND secret=?").bind(counter,user.userId,counter,record.secret).run();if(!accepted.meta.changes)throw new ApiError('This code has already been used. Wait for the next code.',401);return json({ok:true},{'Set-Cookie':await issueSession(user.userId,request)})
}catch(e){if(e instanceof SyntaxError)return apiError(new ApiError('Invalid request.',400));return apiError(e)}}
